# Site settings
title: TEDxBahcesehirUniversity Blog
description: TEDxBahcesehirUniversity Blog Website
keywords: TEDxBahcesehirUniversity, Technology, Entertainment, Design
author: TEDxBahcesehirUniversity Team Members
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://blog.tedxbahcesehir.com" # the base hostname & protocol for your site
